#!/bin/bash
#
# Turns everything under assets/ into src/embedded_assets.h, so the built binary
# carries the font, the level files and the music inside it and needs nothing
# beside it on disk. Run by `make embed`, which every build depends on.
#
# The data is guarded by EMBEDDED_ASSETS_IMPL, and src/assets.c is the single
# translation unit that defines it. Four files include this header — assets.c
# for the data, globals.c for the font, level-manager.c for the levels and
# lib/audio.c for the music — and when the arrays were plain `static const` at
# file scope, each of them compiled its own private copy of every byte of every
# asset. That is what the guard is for: everybody else gets the lookup
# function's prototype and nothing else.

set -euo pipefail

OUTPUT_FILE="src/embedded_assets.h"

# xxd is what turns a file into C. It ships with vim and is not on every box, and
# without this check its absence produced a header full of empty arrays and a
# game that started to a blank screen with no idea why.
command -v xxd >/dev/null || {
    echo "embed_assets: xxd is not installed (it ships with vim)" >&2
    exit 1
}

# Written to a temporary file and moved into place at the end, so that an
# interrupted run leaves the previous header rather than half of a new one.
#
# No `.h` after the X's: BSD mktemp (macOS) only randomises trailing X's, so a
# template with a suffix was one literal filename, and two makes running at
# once - `make test` beside `make release` - failed on "File exists".
tmp=$(mktemp "${TMPDIR:-/tmp}/embedded_assets.XXXXXX")
trap 'rm -f "$tmp"' EXIT

{
    echo "// Auto-generated file - do not edit manually"
    echo "// Generated by embed_assets.sh"
    echo ""
    echo "#pragma once"
    echo "#include <stddef.h>"
    echo ""
    echo "typedef struct {"
    echo "    const char *path;"
    echo "    const unsigned char *data;"
    echo "    size_t size;"
    echo "} EmbeddedAsset;"
    echo ""
    echo "// Defined in src/assets.c, the one translation unit that carries the data."
    echo "const EmbeddedAsset *findEmbeddedAsset(const char *path);"
    echo ""
    echo "#ifdef EMBEDDED_ASSETS_IMPL"
    echo "#include <string.h>"
    echo ""
} > "$tmp"

# Level files and any other asset the game loads by name. -print0/read -d covers
# a path with a space in it, which `for file in $(find ...)` would have split.
#
# .ogg is the music, and it is the reason this header is now tens of megabytes
# of C: nineteen tracks at the quality their composer published them. They are
# in here rather than loaded from disk on purpose - the point of embedding is
# that the soundtrack ships as part of the program and not as nineteen files a
# player can play without it. assets/music/LICENSE.txt comes along for the ride,
# which is the right answer rather than a nuisance: the terms the music arrived
# under end up inside the binary that carries it.
assets=()
while IFS= read -r -d '' file; do
    assets+=("$file")
done < <(LC_ALL=C find assets -type f \( -name "*.bmp" -o -name "*.wav" -o -name "*.ogg" -o -name "*.ttf" -o -name "*.txt" \) -print0 | LC_ALL=C sort -z)

[ ${#assets[@]} -gt 0 ] || {
    echo "embed_assets: found no assets under assets/" >&2
    exit 1
}

# A path becomes a C identifier by turning everything that is not a letter or a
# digit into an underscore, and that is not one-to-one: assets/a-b.txt and
# assets/a_b.txt are the same array. The compiler would say so, as a redefinition
# forty megabytes into a generated header; better said here, with both names.
# (Not an associative array: macOS's /bin/bash is 3.2 and has none.)
varname_of() { echo "$1" | sed 's/[^a-zA-Z0-9]/_/g'; }
dupes=$(for file in "${assets[@]}"; do varname_of "$file"; done \
    | LC_ALL=C sort | uniq -d)
if [ -n "$dupes" ]; then
    for dupe in $dupes; do
        echo "embed_assets: more than one asset becomes the identifier $dupe:" >&2
        for file in "${assets[@]}"; do
            if [ "$(varname_of "$file")" = "$dupe" ]; then
                echo "              $file" >&2
            fi
        done
    done
    echo "embed_assets: rename one of each pair" >&2
    exit 1
fi

for file in "${assets[@]}"; do
    varname=$(varname_of "$file")

    {
        echo "// $file"
        echo "static const unsigned char ${varname}[] = {"
        xxd -i < "$file"
        echo "};"
        echo ""
    } >> "$tmp"
done

{
    echo "static const EmbeddedAsset embeddedAssets[] = {"
} >> "$tmp"

for file in "${assets[@]}"; do
    varname=$(varname_of "$file")
    echo "    { \"$file\", ${varname}, sizeof(${varname}) }," >> "$tmp"
done

{
    echo "    { NULL, NULL, 0 }"
    echo "};"
    echo ""
    echo "const EmbeddedAsset *findEmbeddedAsset(const char *path) {"
    echo "    for (int i = 0; embeddedAssets[i].path != NULL; i++) {"
    echo "        if (strcmp(embeddedAssets[i].path, path) == 0) {"
    echo "            return &embeddedAssets[i];"
    echo "        }"
    echo "    }"
    echo "    return NULL;"
    echo "}"
    echo ""
    echo "#endif // EMBEDDED_ASSETS_IMPL"
} >> "$tmp"

# mktemp makes the file 0600 and mv keeps that; a generated source file should
# read like the rest of the tree.
chmod 644 "$tmp"

# The header is only replaced if it actually changed.
#
# It is 113 MB and four translation units include it, so its mtime is expensive:
# moving a freshly written temp file into place gives it a new one whatever is
# inside, the depfiles see a header newer than their objects, and assets.c,
# globals.c, level-manager.c and audio.c all recompile for a file whose contents
# are byte-for-byte what they already were. The output is deterministic
# (`find | sort -z` under LC_ALL=C, so the order does not follow the locale, and
# xxd of bytes that did not change), so "same contents" is
# the ordinary case rather than a lucky one - `touch`ing a level file, or a
# checkout that rewrites one, should not cost a rebuild.
#
# The touch is what stops make asking again on the next build: this script is
# the recipe for the header, so make compares it against assets/ by mtime, and a
# target left older than its prerequisite is a recipe that runs forever.
if cmp -s "$tmp" "$OUTPUT_FILE"; then
    rm -f "$tmp"
    trap - EXIT
    touch "$OUTPUT_FILE"
    echo "$OUTPUT_FILE is unchanged (${#assets[@]} assets)"
    exit 0
fi

mv "$tmp" "$OUTPUT_FILE"
trap - EXIT

echo "Generated $OUTPUT_FILE with ${#assets[@]} assets"
