// The one translation unit that carries the embedded assets.
//
// embedded_assets.h is generated by embed_assets.sh and holds every byte of the
// font and the level files. Its arrays are `static const` at file scope, so each
// file that included it compiled a private copy of all of them — which is what
// this file and the guard below are for: the data is built once here, and
// globals.c and level-manager.c include the same header for the prototype of
// findEmbeddedAsset() and nothing more.

#define EMBEDDED_ASSETS_IMPL
#include "embedded_assets.h"
